02/12/2019 17:05:45 program started
02/12/2019 17:05:45 command line: /home/mushalali/bin/srst2 --input_se test1.fq --output test1_srst2 --gene_db ARGannot_r3.fasta
02/12/2019 17:05:45 Total single reads found:1
02/12/2019 17:05:49 Building bowtie2 index for ARGannot_r3.fasta...
02/12/2019 17:05:49 Running: bowtie2-build ARGannot_r3.fasta ARGannot_r3.fasta
Error: could not open ARGannot_r3.fasta
Error: Encountered internal Bowtie 2 exception (#1)
Command: bowtie2-build ARGannot_r3.fasta ARGannot_r3.fasta 
Traceback (most recent call last):
  File "/home/mushalali/bin/srst2", line 11, in <module>
    load_entry_point('srst2==0.2.0', 'console_scripts', 'srst2')()
  File "/home/mushalali/.local/lib/python2.7/site-packages/srst2/srst2.py", line 1727, in main
    bowtie_index(args.gene_db) # index the gene databases
  File "/home/mushalali/.local/lib/python2.7/site-packages/srst2/srst2.py", line 155, in bowtie_index
    run_command([get_bowtie_execs()[1], fasta, fasta])
  File "/home/mushalali/.local/lib/python2.7/site-packages/srst2/srst2.py", line 143, in run_command
    raise CommandError({"message": message})
srst2.srst2.CommandError: {'message': "Command 'bowtie2-build ARGannot_r3.fasta ARGannot_r3.fasta' failed with non-zero exit status: 1"}
